import Link from "next/link";
import type { Metadata } from "next";
export const metadata: Metadata = { title: "Quizzes to play with friends", description: "Make a quiz about yourself, fool your friends with a trivia bluff, compare personality results, or collect your group's results in a room.", alternates: { canonical: "/friends/" } };
const activities = [
  { href: "/friend-quiz/", label: "Make a quiz about you", prompt: "Who knows you best?", description: "Choose your answers, send the link, and see how well your friends know you.", action: "Make a friend quiz", tone: "pink" },
  { href: "/fool/", label: "Write a convincing wrong answer", prompt: "Can they spot your bluff?", description: "Add your own fake answers to trivia questions. Challenge your friends to pick the truth.", action: "Fool your friends", tone: "coral" },
  { href: "/compare/", label: "Compare two personalities", prompt: "Where do you see eye to eye?", description: "Take the same personality quiz, then bring your result links together for a side-by-side comparison.", action: "Compare results", tone: "blue" },
  { href: "/room/", label: "Bring the whole group", prompt: "Everyone has a role.", description: "Create or join a room to collect personality results. Share an updated link as your group adds theirs.", action: "Create or join a room", tone: "teal" },
];
export default function FriendsPage() { return <div className="section directory-page"><p className="eyebrow">With friends</p><h1 className="section-title">Give the group chat a quiz.</h1><p className="section-lead">Pick something to make, guess, or compare. Everyone can play on their own phone.</p><div className="friends-grid">{activities.map(activity => <article key={activity.href} className={`friend-activity tone-${activity.tone}`}><p className="eyebrow">{activity.label}</p><h2>{activity.prompt}</h2><p>{activity.description}</p><Link href={activity.href} className="btn-outline">{activity.action} <span aria-hidden="true">→</span></Link></article>)}</div><aside className="directory-note"><h2>Need a personality quiz to compare?</h2><p>Start with <Link href="/test/friend-role/" className="text-link">Friend Role</Link> or <Link href="/test/social-battery/" className="text-link">Social Battery</Link>. Take it separately, then swap results.</p></aside></div>; }
