import type { Metadata } from "next";
import { getTest, TESTS } from "@/lib/tests/registry";
import { getSeoTitle, SEO_TITLES } from "@/lib/seo-titles";
import { SITE } from "@/lib/site";
import { breadcrumbList, jsonLdGraph, quizNode } from "@/lib/structured-data";
import { TestIntroClient } from "./TestIntroClient";

export function generateStaticParams() {
  return TESTS.map((t) => ({ slug: t.slug }));
}

// Headline titles live in seo-titles.ts and feed the <title> and og:title
// ONLY. The on-page H1, the slug, and share cards keep test.title.
export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const test = getTest(slug);
  if (!test) return { title: "Quiz" };

  const seoTitle = getSeoTitle(slug, test.title);
  // Per-quiz OG card generated by scripts/generate-og-cards.mjs (prebuild);
  // cards exist exactly for the slugs in the SEO title map, so anything
  // unmapped falls back to the site-wide default card.
  const ogImage =
    slug in SEO_TITLES ? `${SITE.url}/og/test-${slug}.png` : `${SITE.url}${SITE.ogImage}`;
  return {
    title: seoTitle,
    description: test.description,
    alternates: { canonical: `/test/${slug}/` },
    openGraph: {
      title: `${seoTitle} · ${SITE.legalName}`,
      description: test.description,
      url: `${SITE.url}/test/${slug}/`,
      images: [{ url: ogImage, width: 1200, height: 630, alt: seoTitle }],
    },
    twitter: {
      card: "summary_large_image",
      title: `${seoTitle} · ${SITE.legalName}`,
      description: test.description,
      images: [ogImage],
    },
  };
}

export default async function TestIntroPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const test = getTest(slug);

  // Quiz + BreadcrumbList, matching what the trivia pages emit so the two
  // sections cannot drift apart. Question text and scoring keys stay out of
  // the markup - it describes the page, it does not give the quiz away.
  //
  // No aggregateRating, review, or vote counts anywhere: there are no ratings
  // to report, and inventing them is both a lie and a Google manual action.
  const jsonLd = test
    ? jsonLdGraph([
        quizNode({
          path: `/test/${test.slug}/`,
          name: getSeoTitle(test.slug, test.title),
          description: test.description,
          numberOfQuestions: test.itemCount,
          timeRequiredMinutes: test.timeMinutes,
          educationalUse: "self-reflection",
          audienceType: "Teens and adults",
          about: test.title,
          note: test.disclaimer,
        }),
        breadcrumbList([
          { name: "Home", path: "/" },
          { name: "Quizzes", path: "/tests/" },
          { name: test.title, path: `/test/${test.slug}/` },
        ]),
      ])
    : null;

  return (
    <>
      {jsonLd && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      )}
      <TestIntroClient />
    </>
  );
}
