import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { TESTS } from "../src/lib/tests/registry";
import { JURISDICTIONS } from "../src/lib/driving/jurisdictions";
import { TRIVIA_QUIZZES } from "../src/lib/trivia/registry";
import { EDITIONS, latestEditions, getLatestSeriesEdition } from "../src/lib/newsquiz/editions";
import { editionPath } from "../src/lib/editorial/identity";

// Build-time imports only. The browser gets public paths/IDs, never quiz banks.
const paths = new Set<string>(["/404/"]);
function walk(dir: string) {
  for (const item of readdirSync(dir, { withFileTypes: true })) {
    const file = join(dir, item.name);
    if (item.isDirectory()) walk(file);
    else if (item.name === "page.tsx") {
      const route = relative("src/app", dir).split("/").filter(Boolean);
      if (!route.some(part => part.includes("["))) paths.add(`/${route.join("/")}${route.length ? "/" : ""}`);
    }
  }
}
walk("src/app");
for (const test of TESTS) for (const suffix of ["", "take/", "results/"]) paths.add(`/test/${test.slug}/${suffix}`);
for (const j of JURISDICTIONS) {
  paths.add(`/driving/${j.slug}/`);
  for (const id of [...j.sets.map(s => s.id), "weak-spots", "retry-missed"])
    for (const suffix of ["take", "results"]) paths.add(`/driving/${j.slug}/${id}/${suffix}/`);
}
for (const quiz of TRIVIA_QUIZZES) paths.add(`/trivia/${quiz.slug}/`);
for (const edition of EDITIONS) paths.add(editionPath(edition));
const aliases: Record<string, string> = {};
for (const edition of latestEditions()) {
  const alias = `/weekly/${edition.id}/`;
  paths.add(alias); aliases[alias] = editionPath(edition);
}
for (const series of ["news-world", "news-north-america"]) {
  const edition = getLatestSeriesEdition(series);
  if (edition) aliases[`/trivia/${series}/`] = editionPath(edition);
}
const policy = JSON.parse(readFileSync("content/publication-policy.json", "utf8"));
const series = [...new Set([...EDITIONS.map(e => e.seriesId), ...policy.series])].sort();
const output = `// Generated by scripts/generate-analytics-manifest.ts. Public routing IDs only.\nexport const analyticsPaths: readonly string[] = ${JSON.stringify([...paths].sort())};\nexport const analyticsAliases: Readonly<Record<string, string>> = ${JSON.stringify(aliases)};\nexport const analyticsEditions: readonly { id: string; seriesId: string; version: number }[] = ${JSON.stringify(EDITIONS.map(({ id, seriesId, version }) => ({ id, seriesId, version })))};\nexport const analyticsSeries: readonly string[] = ${JSON.stringify(series)};\n`;
const destination = "src/lib/analytics-manifest.generated.ts";
if (process.argv.includes("--check")) {
  if (readFileSync(destination, "utf8") !== output) throw new Error("Analytics route manifest is stale; run npm run generate:analytics");
} else writeFileSync(destination, output);
console.log(`Analytics manifest ${process.argv.includes("--check") ? "checked" : "generated"}: ${paths.size} public routes`);
