// GENERATED by scripts/generate-driving-summary.mjs - do not edit by hand.
//
// A light index of the driving jurisdictions: no questions, no handbook quotes.
// Client components import THIS rather than jurisdictions.ts, which would drag
// the whole corpus into the browser bundle. See the generator for the measured
// reason why.

export interface JurisdictionSummary {
  slug: string;
  name: string;
  code: string;
  country: "CA" | "US";
  licenceName: string;
  intro: string;
  contentDate: string;
  setCount: number;
  questionCount: number;
}

export const JURISDICTION_SUMMARIES: JurisdictionSummary[] = [
  {
    "slug": "alberta",
    "name": "Alberta",
    "code": "AB",
    "country": "CA",
    "licenceName": "Class 7 Learner's Licence",
    "intro": "Alberta's Class 7 knowledge test is 30 questions, and it stops the moment you've got 25 right or 6 wrong. These sets build up to that.",
    "contentDate": "2026-08-11",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "ontario",
    "name": "Ontario",
    "code": "ON",
    "country": "CA",
    "licenceName": "G1 Licence",
    "intro": "The G1 knowledge test is commonly delivered as two 20-question sections - road signs and rules of the road. We practise them separately so a strong half can't hide a weak one.",
    "contentDate": "2026-08-11",
    "setCount": 6,
    "questionCount": 220
  },
  {
    "slug": "texas",
    "name": "Texas",
    "code": "TX",
    "country": "US",
    "licenceName": "Texas Driver License",
    "intro": "Texas passes at 70% - the most forgiving mark in the US - but the questions still come straight out of the handbook.",
    "contentDate": "2026-08-11",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "florida",
    "name": "Florida",
    "code": "FL",
    "country": "US",
    "licenceName": "Class E Learner License",
    "intro": "Florida asks 50 questions and wants 40 right. The insurance rules catch people out - it is a no-fault state, so the minimums it tests are not the ones most drivers expect.",
    "contentDate": "2026-08-14",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "newyork",
    "name": "New York",
    "code": "NY",
    "country": "US",
    "licenceName": "Learner Permit",
    "intro": "New York has a second hurdle most people miss: 14 of 20 passes, but miss three of the four road-sign questions and you fail anyway.",
    "contentDate": "2026-08-14",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "pennsylvania",
    "name": "Pennsylvania",
    "code": "PA",
    "country": "US",
    "licenceName": "Learner's Permit",
    "intro": "Pennsylvania asks only 18 questions but wants 15 right, so there is almost no room to guess - one of the tightest margins anywhere.",
    "contentDate": "2026-08-14",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "ohio",
    "name": "Ohio",
    "code": "OH",
    "country": "US",
    "licenceName": "Temporary Instruction Permit (TIPIC)",
    "intro": "Ohio asks 40 questions and passes at 75%. Watch the probationary night hours - they change after your first year, not on your birthday.",
    "contentDate": "2026-08-14",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "georgia",
    "name": "Georgia",
    "code": "GA",
    "country": "US",
    "licenceName": "Class CP Instructional Permit",
    "intro": "Georgia scores road signs and road rules as two separate exams of 20, and you need 15 in each. Ace the rules and fluff the signs and you still fail.",
    "contentDate": "2026-08-14",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "illinois",
    "name": "Illinois",
    "code": "IL",
    "country": "US",
    "licenceName": "Instruction Permit",
    "intro": "Scott's Law is the single most-missed topic in Illinois, and the penalties are far heavier than people expect. These sets lean into it.",
    "contentDate": "2026-08-14",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "northcarolina",
    "name": "North Carolina",
    "code": "NC",
    "country": "US",
    "licenceName": "Learner Permit",
    "intro": "North Carolina runs the signs test as a separate exam, and several of its rules are the opposite of what drivers from other states expect - the horn before overtaking, two feet of passing clearance, two seconds of following distance.",
    "contentDate": "2026-08-14",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "michigan",
    "name": "Michigan",
    "code": "MI",
    "country": "US",
    "licenceName": "Temporary Instruction Permit",
    "intro": "Michigan runs the test as two separately-scored parts - operator rules and signs - and you have to clear both. Pass one and fail the other and you retake the whole thing.",
    "contentDate": "2026-08-14",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "newjersey",
    "name": "New Jersey",
    "code": "NJ",
    "country": "US",
    "licenceName": "Student Learner's Permit",
    "intro": "New Jersey has more genuinely unusual rules than any other state here - it legislates for ice cream trucks, sets the curfew at 11:01pm, and declines to state a priority rule for traffic circles at all.",
    "contentDate": "2026-08-14",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "virginia",
    "name": "Virginia",
    "code": "VA",
    "country": "US",
    "licenceName": "Learner's Permit",
    "intro": "Virginia gates the whole exam behind signs: all ten sign questions must be right before the 30-question second part even opens. Miss one and you are done for the day.",
    "contentDate": "2026-08-14",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "california",
    "name": "California",
    "code": "CA",
    "country": "US",
    "licenceName": "California Driver License / Permit",
    "intro": "California leans hard on parking rules - coloured curbs and which way your wheels point on a hill show up far more than people expect.",
    "contentDate": "2026-08-11",
    "setCount": 6,
    "questionCount": 231
  },
  {
    "slug": "washington",
    "name": "Washington",
    "code": "WA",
    "country": "US",
    "licenceName": "Instruction Permit",
    "intro": "Washington's guide is unusually plain-spoken, which cuts both ways: it states some rules as memory aids rather than law, and it leaves out numbers the test still asks for.",
    "contentDate": "2026-08-15",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "massachusetts",
    "name": "Massachusetts",
    "code": "MA",
    "country": "US",
    "licenceName": "Class D Learner's Permit",
    "intro": "The shortest exam on this site, and the least forgiving: 25 questions in 25 minutes, and a Junior Operator licence that punishes a single speeding ticket harder than most states punish three.",
    "contentDate": "2026-08-15",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "tennessee",
    "name": "Tennessee",
    "code": "TN",
    "country": "US",
    "licenceName": "Class D Learner Permit",
    "intro": "Tennessee is the rare state that tells you the syllabus but not the score: the manual publishes an exact topic split and no question count at all.",
    "contentDate": "2026-08-15",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "arizona",
    "name": "Arizona",
    "code": "AZ",
    "country": "US",
    "licenceName": "Instruction Permit",
    "intro": "Arizona teaches two things no other manual does, and both run opposite to instinct: in a dust storm you turn your lights off, and driving around a flood barricade makes you pay for your own rescue.",
    "contentDate": "2026-08-15",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "britishcolumbia",
    "name": "British Columbia",
    "code": "BC",
    "country": "CA",
    "licenceName": "Class 7L Learner's Licence",
    "intro": "A flashing green light means the opposite here to what it means in Alberta, Ontario and the Maritimes - and that single sign catches more drivers moving to BC than anything else in the guide.",
    "contentDate": "2026-08-15",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "indiana",
    "name": "Indiana",
    "code": "IN",
    "country": "US",
    "licenceName": "Learner's Permit",
    "intro": "Indiana words its tie-break backwards from everywhere else: at an all-way stop it is the vehicle on the LEFT that yields. Then at a dark signal it flips back.",
    "contentDate": "2026-08-15",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "missouri",
    "name": "Missouri",
    "code": "MO",
    "country": "US",
    "licenceName": "Class F Instruction Permit",
    "intro": "The Missouri Driver Guide tells you something no other state prints: almost half of everyone who sits this test fails it the first time.",
    "contentDate": "2026-08-15",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "maryland",
    "name": "Maryland",
    "code": "MD",
    "country": "US",
    "licenceName": "Learner's Permit",
    "intro": "The strictest pass mark on this site: 88%, which on a 25-question test means you may get three wrong and no more.",
    "contentDate": "2026-08-15",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "alabama",
    "name": "Alabama",
    "code": "AL",
    "country": "US",
    "licenceName": "Learner License",
    "intro": "Alabama's knowledge test is written straight out of the ALEA Driver Manual, and the manual says so in as many words: the test is taken from material found in this booklet. It is one of the more complete state handbooks - it prints the statutory speed limits, the parking distances and the point schedule - but it never states how many questions the test has or what score passes, so this bank covers the whole book rather than betting on a section.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "colorado",
    "name": "Colorado",
    "code": "CO",
    "country": "US",
    "licenceName": "Instruction Permit",
    "intro": "A short handbook with a long memory for numbers: Colorado's test asks the school-bus distance, the headlight rule, the mountain-road tie-breaker and the under-21 alcohol limit that the 27-page book states exactly once each.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "connecticut",
    "name": "Connecticut",
    "code": "CT",
    "country": "US",
    "licenceName": "Learner's Permit (Class D)",
    "intro": "Connecticut's learner's permit test is 25 questions and you need 20 right - four wrong and you are still fine, five and you come back in a week. The DMV writes it from the Connecticut Driver's Manual, and the questions people actually lose are the teen driving rules and the exact numbers. Everything below is checked against the March 2023 manual and, where the manual leaves a number out, against Connecticut General Statutes Title 14.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "iowa",
    "name": "Iowa",
    "code": "IA",
    "country": "US",
    "licenceName": "Instruction Permit",
    "intro": "Iowa lets you start at 14, which is younger than almost anywhere else, and the knowledge test is the only thing standing between you and an instruction permit. Everything below is written from the Iowa Driver's License Manual dated 07/23/2026 and, where the manual leaves a number out, from Iowa Code chapter 321 and the licensing rules in 761 Iowa Administrative Code chapter 604.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "kentucky",
    "name": "Kentucky",
    "code": "KY",
    "country": "US",
    "licenceName": "Instruction Permit",
    "intro": "Kentucky splits the job between two agencies: you apply at a Transportation Cabinet regional driver licensing office, and the Kentucky State Police give you the vision screening and the written test. The manual is the only study source KSP endorses, and it says the pass mark is 80 percent. Everything below is written from the Kentucky Driver Manual dated 10-11-2023 and, where the manual leaves a number out, from KRS chapters 186, 189 and 189A.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "louisiana",
    "name": "Louisiana",
    "code": "LA",
    "country": "US",
    "licenceName": "Class E Learner's Permit",
    "intro": "Louisiana's knowledge test is 40 multiple-choice questions and you need 32 of them right. It is written from the Class D & E Driver's Guide, and in most cases your driving school gives it to you rather than the OMV. Everything below is checked against that guide and, where the guide leaves a number out, against Revised Statutes Title 32 and the OMV's own licensing handouts.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "manitoba",
    "name": "Manitoba",
    "code": "MB",
    "country": "CA",
    "licenceName": "Class 5L Learner Stage Licence",
    "intro": "Manitoba Public Insurance writes the Class 5 knowledge test straight out of its own Driver's Handbook, and the parts that catch people are the numbers - how far back from a railway crossing, how far from a hydrant, how many months in each stage. You get 30 minutes, it is not open book, and a fail means waiting seven days. These six sets work through the handbook end to end and then hand you the ones Manitobans say they got wrong.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "minnesota",
    "name": "Minnesota",
    "code": "MN",
    "country": "US",
    "licenceName": "Class D Instruction Permit",
    "intro": "Minnesota's Class D knowledge test is written straight out of the Driver's Manual, and DVS says so: its own practice test tells you every answer is in the book. What catches people is the Minnesota-specific geometry - J-turns, zipper merges, bus shoulders - and the pile of distance numbers the manual prints without ever putting them in one place.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "nevada",
    "name": "Nevada",
    "code": "NV",
    "country": "US",
    "licenceName": "Class C Instruction Permit",
    "intro": "Nevada's knowledge test is 25 multiple-choice questions and you need 20 right. It is short, which makes it unforgiving: five wrong answers is the whole margin, and the test stops the moment you reach six. Everything below is written from the March 2024 Nevada Driver's Handbook and, where the handbook leaves a number out, from the Nevada Revised Statutes.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "oklahoma",
    "name": "Oklahoma",
    "code": "OK",
    "country": "US",
    "licenceName": "Class D Learner Permit",
    "intro": "Oklahoma's written knowledge test is 20 questions and you need 15 right, with 60 minutes on the clock. Everything below is written from the Oklahoma Driver Manual that Service Oklahoma publishes, and where the manual leaves a number out, from Title 47 of the Oklahoma Statutes and Service Oklahoma's own licensing pages.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "oregon",
    "name": "Oregon",
    "code": "OR",
    "country": "US",
    "licenceName": "Class C Instruction Permit",
    "intro": "Oregon's Class C knowledge test is 35 multiple-choice questions and you need 28 right - 80 percent. You can sit it at a DMV office on a touch screen or at home on a laptop with a webcam, and if you are under 18 the home version needs an adult proctor over 21. Everything below is written from the 2026-2027 Oregon Driver Manual and, where the manual leaves a number out, from Oregon Revised Statutes chapters 807, 811 and 813.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "quebec",
    "name": "Quebec",
    "code": "QC",
    "country": "CA",
    "licenceName": "Class 5 Learner's Licence",
    "intro": "Quebec's knowledge test is run by the SAAQ and scored in three separate sections, and you have to clear 75% in each one. About half of it is illustrated situations where you are asked which vehicles are breaking a rule, so knowing the rule is only half the job - you also have to spot the detail in the picture. These six sets cover the Highway Safety Code, the signs and signals, and the driving behaviour the third section asks about.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "southcarolina",
    "name": "South Carolina",
    "code": "SC",
    "country": "US",
    "licenceName": "Beginner's Permit",
    "intro": "South Carolina's beginner's permit knowledge test is written from the SCDMV Driver's License Manual, a 141-page book built on the AAMVA model manual. The manual leaves out most of the numbers people expect - every speed limit, every parking distance, the adult BAC limit - so this bank fills those from Title 56 of the South Carolina Code and tells you where each one came from.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "utah",
    "name": "Utah",
    "code": "UT",
    "country": "US",
    "licenceName": "Learner Permit",
    "intro": "Utah's learner permit test is 50 questions, closed book, and marked at 80 percent - and it is only the first of two written hurdles, because every first-time driver also has to score 100 percent on the online Traffic Safety and Trends Exam before the license is issued. Everything below is written from the 2026-2027 Utah Driver Handbook and, where the handbook leaves a number out, from Title 41 Chapter 6a of the Utah Code.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  },
  {
    "slug": "wisconsin",
    "name": "Wisconsin",
    "code": "WI",
    "country": "US",
    "licenceName": "Class D Instruction Permit",
    "intro": "Wisconsin runs two separate written tests at the DMV, and you have to clear both: a 50-question knowledge test on the rules and a 15-question highway signs test. Both are marked at 80 percent. Everything below is written from the 2026 Wisconsin Motorists' Handbook and, where the handbook leaves a number out, from Wisconsin Statutes chapters 343 and 346.",
    "contentDate": "2026-09-06",
    "setCount": 6,
    "questionCount": 195
  }
];

/** Total practice questions across every jurisdiction. */
export const TOTAL_DRIVING_QUESTIONS = 7276;
